### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by tednaphil** [tednaphil/FitLit#24]
As an employer or developer, when I visit the repo README, I should be able see:

- An abstract describing the project
- An overview of project goals
- List of technologies used
- Context - challenges, wins, time worked, and any other reflections
- Preview of app (gif or screenshot)
- List of contributors

**Comment by cOdeBedient** [comment]
Let's start this before Monday!

**Comment by tednaphil** [comment]
I've started a draft in the feature/README-tp branch
