### ISSUE TITLE
Make user info page

### ISSUE THREAD

**Issue by pareesakd1118** [tednaphil/FitLit#63]
Make user info page you can navigate to with button that has email, address and friends (stride length maybe?)

**Comment by tednaphil** [comment]
- button in header bar added to toggle between profile and home page
- "profile" displays friends list, address, and email
- Richard is the default profile photo 😄 
- some extraneous elements and styles remain that are up for deletion if we choose not to use them (original email and address layout & experimental detail disclosure elements)

**Comment by tednaphil** [comment]
Merged the most up to date work into my branch, so it now includes everyone's work on the graphs and new footer form!
